import { ApiProperty } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  ArrayNotEmpty,
  ArrayUnique,
  IsArray,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

/**
 * Upper bounds mirroring the `fanzones` columns on FanzoneEntity, so validation
 * rejects what the database could not store.
 */
export const FANZONE_NAME_MAX_LENGTH = 255;
export const FANZONE_ADDRESS_MAX_LENGTH = 500;
export const FANZONE_CITY_MAX_LENGTH = 255;

/**
 * Cap on the AI-generated description. The column is `text` (unbounded), so this
 * is a product limit rather than a storage one: it keeps generated copy short
 * enough to render in a map popup.
 */
export const FANZONE_DESCRIPTION_MAX_LENGTH = 1000;

/**
 * Capacity bounds. The minimum is a product rule — a venue holding fewer than
 * ten people is not a fan zone. The maximum is the `integer` column's ceiling:
 * without it, a larger value passes validation and fails at the driver with
 * "integer out of range".
 */
export const FANZONE_CAPACITY_MIN = 10;
export const FANZONE_CAPACITY_MAX = 2147483647;

/** Teams contesting the 2026 World Cup — an upper bound on `teamIds`. */
export const FANZONE_MAX_TEAMS = 48;

/**
 * Strict 24-hour `HH:mm`, matching the `time` columns.
 *
 * Deliberately not `@IsMilitaryTime()`: its regex is
 * `/^([01]\d|2[0-3]):?([0-5]\d)$/` — the `:?` makes the colon optional, so it
 * accepts `"1800"`. Keep this stricter pattern.
 */
export const TIME_PATTERN = /^([01]\d|2[0-3]):[0-5]\d$/;

/**
 * Request body for creating a fan zone.
 *
 * Requirement: EF-08 — fan zones are displayed on a map.
 * Requirement: EF-09 — distance, capacity and broadcast teams are shown.
 *
 * Two rules deliberately live outside this DTO:
 * - **Team existence** is checked by the service layer; class-validator has no
 *   database access.
 * - **Opening/closing order** is NOT enforced. The pair describes a wrapping
 *   interval, so a zone open `18:00`–`00:00` (or `20:00`–`02:00` for a late
 *   kick-off) is valid. Only the `HH:mm` format is validated here.
 */
export class CreateFanzoneDto {
  @ApiProperty({
    description: 'Display name of the fan zone',
    example: 'Doha Corniche Fan Zone',
    maxLength: FANZONE_NAME_MAX_LENGTH,
  })
  @IsString()
  @IsNotEmpty({ message: 'Name is required' })
  @MaxLength(FANZONE_NAME_MAX_LENGTH, {
    message: `Name must be at most ${FANZONE_NAME_MAX_LENGTH} characters long`,
  })
  name!: string;

  /**
   * Optional on input: descriptions are generated by the AI pipeline after
   * creation, so an admin need not write one.
   */
  @ApiProperty({
    description: 'Free-text description; generated by the AI pipeline when omitted',
    example: 'Open-air zone on the Corniche with a 40m screen and food trucks.',
    maxLength: FANZONE_DESCRIPTION_MAX_LENGTH,
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(FANZONE_DESCRIPTION_MAX_LENGTH, {
    message: `Description must be at most ${FANZONE_DESCRIPTION_MAX_LENGTH} characters long`,
  })
  description?: string;

  /**
   * Note: no `maxDecimalPlaces` option. class-validator implements it as
   * `value.toString().split('.')[1].length`, which throws a TypeError for any
   * value below 1e-6 (it stringifies to exponential form, e.g. `1e-7`) — a valid
   * near-equator coordinate would surface as a 500. The `numeric(10,8)` column
   * rounds excess scale on its own, so the option bought nothing.
   */
  @ApiProperty({
    description: 'Latitude in decimal degrees (WGS 84)',
    example: 25.2854,
    minimum: -90,
    maximum: 90,
  })
  @IsNumber({}, { message: 'latitude must be a number' })
  @Min(-90, { message: 'latitude must not be less than -90' })
  @Max(90, { message: 'latitude must not be greater than 90' })
  latitude!: number;

  @ApiProperty({
    description: 'Longitude in decimal degrees (WGS 84)',
    example: 51.5310,
    minimum: -180,
    maximum: 180,
  })
  @IsNumber({}, { message: 'longitude must be a number' })
  @Min(-180, { message: 'longitude must not be less than -180' })
  @Max(180, { message: 'longitude must not be greater than 180' })
  longitude!: number;

  @ApiProperty({
    description: 'Maximum number of people the fan zone can host',
    example: 5000,
    minimum: FANZONE_CAPACITY_MIN,
    maximum: FANZONE_CAPACITY_MAX,
  })
  @IsInt({ message: 'capacity must be an integer' })
  @Min(FANZONE_CAPACITY_MIN, {
    message: `capacity must be at least ${FANZONE_CAPACITY_MIN}`,
  })
  @Max(FANZONE_CAPACITY_MAX, {
    message: `capacity must be at most ${FANZONE_CAPACITY_MAX}`,
  })
  capacity!: number;

  @ApiProperty({
    description: 'Street address of the fan zone',
    example: 'Al Corniche Street, Doha',
    maxLength: FANZONE_ADDRESS_MAX_LENGTH,
  })
  @IsString()
  @IsNotEmpty({ message: 'Address is required' })
  @MaxLength(FANZONE_ADDRESS_MAX_LENGTH, {
    message: `Address must be at most ${FANZONE_ADDRESS_MAX_LENGTH} characters long`,
  })
  address!: string;

  @ApiProperty({
    description: 'City the fan zone is located in',
    example: 'Doha',
    maxLength: FANZONE_CITY_MAX_LENGTH,
  })
  @IsString()
  @IsNotEmpty({ message: 'City is required' })
  @MaxLength(FANZONE_CITY_MAX_LENGTH, {
    message: `City must be at most ${FANZONE_CITY_MAX_LENGTH} characters long`,
  })
  city!: string;

  @ApiProperty({
    description: 'Opening time in 24-hour HH:mm format',
    example: '18:00',
    pattern: '^([01]\\d|2[0-3]):[0-5]\\d$',
    required: false,
  })
  @IsOptional()
  @Matches(TIME_PATTERN, {
    message: 'openingHour must be a time in HH:mm format (00:00 to 23:59)',
  })
  openingHour?: string;

  /**
   * May be earlier than `openingHour` — see the class doc: the pair is a
   * wrapping interval, not an ordered range.
   */
  @ApiProperty({
    description:
      'Closing time in 24-hour HH:mm format; may be earlier than openingHour for zones open past midnight',
    example: '00:00',
    pattern: '^([01]\\d|2[0-3]):[0-5]\\d$',
    required: false,
  })
  @IsOptional()
  @Matches(TIME_PATTERN, {
    message: 'closingHour must be a time in HH:mm format (00:00 to 23:59)',
  })
  closingHour?: string;

  @ApiProperty({
    description: 'UUIDs of the teams broadcast at this fan zone (one or more)',
    type: [String],
    format: 'uuid',
    example: [
      '3f0c9b7e-1a2b-4c3d-9e8f-0a1b2c3d4e5f',
      '7a1e2b3c-4d5e-6f70-8192-a3b4c5d6e7f8',
    ],
  })
  @IsArray({ message: 'teamIds must be an array' })
  @ArrayNotEmpty({ message: 'At least one team ID is required' })
  @ArrayUnique({ message: 'teamIds must not contain duplicates' })
  @ArrayMaxSize(FANZONE_MAX_TEAMS, {
    message: `teamIds must contain at most ${FANZONE_MAX_TEAMS} team IDs`,
  })
  @IsUUID('all', { each: true, message: 'Each team ID must be a valid UUID' })
  teamIds!: string[];
}
