import { ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  ArrayNotEmpty,
  ArrayUnique,
  IsArray,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

import { AtLeastOneField } from '../../../common/validators/at-least-one-field.validator';
import {
  FANZONE_ADDRESS_MAX_LENGTH,
  FANZONE_CAPACITY_MAX,
  FANZONE_CAPACITY_MIN,
  FANZONE_CITY_MAX_LENGTH,
  FANZONE_DESCRIPTION_MAX_LENGTH,
  FANZONE_MAX_TEAMS,
  FANZONE_NAME_MAX_LENGTH,
  TIME_PATTERN,
} from './create-fanzone.dto';

/**
 * Partial update of a fan zone — every field of CreateFanzoneDto, all optional.
 *
 * `@AtLeastOneField` rejects an empty `{}` body: a no-op update is almost always
 * a client bug, not an intent. When present, each field is validated with the
 * same rules as on create, reusing the constants and pattern declared there.
 *
 * `teamIds` keeps `@ArrayNotEmpty`: a supplied array *replaces* the broadcast
 * set, and a fan zone must always broadcast at least one team, so `[]` is
 * rejected rather than read as "clear all teams". Omit the field to leave the
 * existing teams untouched.
 *
 * Deliberately NOT derived via `PartialType(CreateFanzoneDto)`: writing the
 * fields out keeps the optionality and the at-least-one rule visible in one
 * place — matching the convention established by UpdateMatchDto and
 * UpdateTeamDto.
 */
@AtLeastOneField(
  [
    'name',
    'description',
    'latitude',
    'longitude',
    'capacity',
    'availableSpots',
    'address',
    'city',
    'openingHour',
    'closingHour',
    'teamIds',
  ],
  {
    message:
      'At least one of name, description, latitude, longitude, capacity, availableSpots, address, city, openingHour, closingHour, teamIds must be provided',
  },
)
export class UpdateFanzoneDto {
  @ApiPropertyOptional({
    description: 'Display name of the fan zone',
    example: 'Doha Corniche Fan Zone',
    maxLength: FANZONE_NAME_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(FANZONE_NAME_MAX_LENGTH, {
    message: `Name must be at most ${FANZONE_NAME_MAX_LENGTH} characters long`,
  })
  name?: string;

  @ApiPropertyOptional({
    description:
      'Free-text description; generated by the AI pipeline when omitted',
    example: 'Open-air zone on the Corniche with a 40m screen and food trucks.',
    maxLength: FANZONE_DESCRIPTION_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(FANZONE_DESCRIPTION_MAX_LENGTH, {
    message: `Description must be at most ${FANZONE_DESCRIPTION_MAX_LENGTH} characters long`,
  })
  description?: string;

  @ApiPropertyOptional({
    description: 'Latitude in decimal degrees (WGS 84)',
    example: 25.2854,
    minimum: -90,
    maximum: 90,
  })
  @IsOptional()
  @IsNumber({}, { message: 'latitude must be a number' })
  @Min(-90, { message: 'latitude must not be less than -90' })
  @Max(90, { message: 'latitude must not be greater than 90' })
  latitude?: number;

  @ApiPropertyOptional({
    description: 'Longitude in decimal degrees (WGS 84)',
    example: 51.531,
    minimum: -180,
    maximum: 180,
  })
  @IsOptional()
  @IsNumber({}, { message: 'longitude must be a number' })
  @Min(-180, { message: 'longitude must not be less than -180' })
  @Max(180, { message: 'longitude must not be greater than 180' })
  longitude?: number;

  @ApiPropertyOptional({
    description: 'Maximum number of people the fan zone can host',
    example: 5000,
    minimum: FANZONE_CAPACITY_MIN,
    maximum: FANZONE_CAPACITY_MAX,
  })
  @IsOptional()
  @IsInt({ message: 'capacity must be an integer' })
  @Min(FANZONE_CAPACITY_MIN, {
    message: `capacity must be at least ${FANZONE_CAPACITY_MIN}`,
  })
  @Max(FANZONE_CAPACITY_MAX, {
    message: `capacity must be at most ${FANZONE_CAPACITY_MAX}`,
  })
  capacity?: number;

  @ApiPropertyOptional({
    description:
      'Spots still free; occupancy is derived from capacity minus this value. ' +
      'Normally maintained by check-ins — set it here to correct a drifted count. ' +
      'Takes precedence over the value derived from a capacity change supplied in ' +
      'the same request, and is clamped to the resulting capacity.',
    example: 70,
    minimum: 0,
    maximum: FANZONE_CAPACITY_MAX,
  })
  @IsOptional()
  @IsInt({ message: 'availableSpots must be an integer' })
  @Min(0, { message: 'availableSpots must be at least 0' })
  @Max(FANZONE_CAPACITY_MAX, {
    message: `availableSpots must be at most ${FANZONE_CAPACITY_MAX}`,
  })
  availableSpots?: number;

  @ApiPropertyOptional({
    description: 'Street address of the fan zone',
    example: 'Al Corniche Street, Doha',
    maxLength: FANZONE_ADDRESS_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(FANZONE_ADDRESS_MAX_LENGTH, {
    message: `Address must be at most ${FANZONE_ADDRESS_MAX_LENGTH} characters long`,
  })
  address?: string;

  @ApiPropertyOptional({
    description: 'City the fan zone is located in',
    example: 'Doha',
    maxLength: FANZONE_CITY_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(FANZONE_CITY_MAX_LENGTH, {
    message: `City must be at most ${FANZONE_CITY_MAX_LENGTH} characters long`,
  })
  city?: string;

  @ApiPropertyOptional({
    description: 'Opening time in 24-hour HH:mm format',
    example: '18:00',
    pattern: '^([01]\\d|2[0-3]):[0-5]\\d$',
  })
  @IsOptional()
  @Matches(TIME_PATTERN, {
    message: 'openingHour must be a time in HH:mm format (00:00 to 23:59)',
  })
  openingHour?: string;

  @ApiPropertyOptional({
    description:
      'Closing time in 24-hour HH:mm format; may be earlier than openingHour for zones open past midnight',
    example: '00:00',
    pattern: '^([01]\\d|2[0-3]):[0-5]\\d$',
  })
  @IsOptional()
  @Matches(TIME_PATTERN, {
    message: 'closingHour must be a time in HH:mm format (00:00 to 23:59)',
  })
  closingHour?: string;

  @ApiPropertyOptional({
    description:
      'UUIDs of the teams broadcast at this fan zone; replaces the existing set',
    type: [String],
    format: 'uuid',
    example: [
      '3f0c9b7e-1a2b-4c3d-9e8f-0a1b2c3d4e5f',
      '7a1e2b3c-4d5e-6f70-8192-a3b4c5d6e7f8',
    ],
  })
  @IsOptional()
  @IsArray({ message: 'teamIds must be an array' })
  @ArrayNotEmpty({ message: 'At least one team ID is required' })
  @ArrayUnique({ message: 'teamIds must not contain duplicates' })
  @ArrayMaxSize(FANZONE_MAX_TEAMS, {
    message: `teamIds must contain at most ${FANZONE_MAX_TEAMS} team IDs`,
  })
  @IsUUID('all', { each: true, message: 'Each team ID must be a valid UUID' })
  teamIds?: string[];
}
